#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Fundamentals.Droid.Resource", IsApplication=true)]

namespace Fundamentals.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_focused = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int android_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flag = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_0 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_6 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_7 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int splash_logo = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btnclickcounter = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int gotoactivityb = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int imageView1 = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int lblclickCounter = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Language = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LifecycleActivityA = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LifecycleActivityB = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Orientation = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Rotation = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int activityb = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int hellolang = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
